service:
  ui:
    type: NodePort
    nodePort: 31327

longhornUI:
  replicas: 1

longhornManager:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi