grafana.ini:
  database:
    type: postgres
    host: shared-postgres-cluster-rw.cnpg.svc.cluster:5432
    name: grafana
    user: grafana
    password: $__file{/etc/secrets/postgres/password}

extraSecretMounts:
  - name: postgres-credentials
    secretName: grafana-postgres-credentials
    defaultMode: 0440
    mountPath: /etc/secrets/postgres
    readOnly: true

imageRenderer:
  enabled: true

persistence:
  enabled: false

resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    cpu: 2
    memory: 2Gi