replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

persistence:
  enabled: true
  size: 8Gi

auth:
  enabled: true
  rootUsername: admin
  existingSecret: mongodb-root-credentials
  existingSecretPasswordKey: password