kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr-creds
  labels:
    {{- include "nitter.labels" . | nindent 4 }}
spec:
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"gcr.io\":{\"auth\":\"username:%s\"}}}" ("test" | b64enc) | b64enc }}