apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.imagePullSecret.name }}
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: secrets/artifacts/ghcr
      property: .dockerconfigjson