{{- if .Values.redis.auth.usePasswordFileFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.existingSecret }}
type: Opaque
data:
  redis-password.yaml: {{ printf "%s: %s" .Values.redis.auth.existingSecretPasswordKey "a" | b64enc }}
{{- end }}