kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "nitter.fullname" . }}-twitter-guest-accounts
spec:
data:
  guest_accounts.jsonl: {{ printf "{\"oauth_token\":\"%s\",\"oauth_token_secret\":\"%s\"}" .Values.twitter.oauthToken .Values.twitter.oauthTokenSecret | b64enc }}