kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: twitter-guest-accounts
  labels:
    {{- include "nitter.labels" . | nindent 4 }}
spec:
data:
  guest_accounts.jsonl: {{ .Values.twitter.fullAuthJson | b64enc }}