apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "me2me-awl-be.fullname" . }}
  labels:
    {{- include "me2me-awl-be.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "me2me-awl-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "me2me-awl-be.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "me2me-awl-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "me2me-awl-be.fullname" . }}-env-vars
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.jwtAuth.enabled }}
            - name: public-key
              mountPath: /app/public-key.pem
              subPath: public-key.pem
            - name: private-key
              mountPath: /app/private-key.pem
              subPath: private-key.pem
            {{- end }}
            {{- if .Values.mongoDB.enabled }}
            - name: username
              mountPath: /app/mongodbuser
              subPath: mongodbuser
            - name: password
              mountPath: /app/mongodbpassword
              subPath: mongodbpassword
            {{- end }}
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: storage-{{ include "me2me-awl-be.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.jwtAuth.enabled }}
        - name: public-key
          secret:
            secretName: {{ .Values.jwtAuth.publicKey.secretName }}
        - name: private-key
          secret:
            secretName: {{ .Values.jwtAuth.privateKey.secretName }}
        {{- end }}
        {{- if .Values.mongoDB.enabled }}
        - name: username
          secret:
            secretName: {{ .Values.mongoDB.userSecretName }}
        - name: password
          secret:
            secretName: {{ .Values.mongoDB.passwordSecretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
