apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-external-secret
  namespace: authentik
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-credentials
  data:
  - secretKey: username
    remoteRef:
      key: secrets/authentik/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: secrets/authentik/postgres
      property: password