apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-external-secret
  namespace: grafana
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-postgres-credentials
  data:
  - secretKey: password
    remoteRef:
      key: secrets/grafana/postgres
      property: password