apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-external-secret
  namespace: longhorn
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
    namespace: vault
  target:
    name: longhorn-unas-cifs-secret
  data:
  - secretKey: CIFS_USERNAME
    remoteRef:
      key: secrets/storage/unas
      property: CIFS_USERNAME
  - secretKey: CIFS_PASSWORD
    remoteRef:
      key: secrets/storage/unas
      property: CIFS_PASSWORD