apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: me2me-awl-be-jwt-keys
  namespace: me2me-awl
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: me2me-awl-be-jwt-keys
  data:
    - secretKey: username
      remoteRef:
        key: secrets/mongodb/me2me-awl
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/mongodb/me2me-awl
        property: password