apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-gcs-creds
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: gcs-sa-secret
    template:
      data:
        GCS_CLIENT_EMAIL: '{{ .gcs_client_email }}'
        GCS_PRIVATE_KEY: '{{ .gcs_private_key | replace "\\n" "\n" }}'
  data:
    - secretKey: gcs_private_key
      remoteRef:
        key: secrets/mongodb/gcs-creds
        property: private_key
    - secretKey: gcs_client_email
      remoteRef:
        key: secrets/mongodb/gcs-creds
        property: email