---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-system-secrets
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: mongodb-system-secrets
  data:
    - secretKey: MONGODB_BACKUP_USER
      remoteRef:
        key: secrets/mongodb/system
        property: backup_user
    - secretKey: MONGODB_BACKUP_PASSWORD
      remoteRef:
        key: secrets/mongodb/system
        property: backup_password
    - secretKey: MONGODB_DATABASE_ADMIN_USER
      remoteRef:
        key: secrets/mongodb/system
        property: database_admin_user
    - secretKey: MONGODB_DATABASE_ADMIN_PASSWORD
      remoteRef:
        key: secrets/mongodb/system
        property: database_admin_password
    - secretKey: MONGODB_CLUSTER_ADMIN_USER
      remoteRef:
        key: secrets/mongodb/system
        property: cluster_admin_user
    - secretKey: MONGODB_CLUSTER_ADMIN_PASSWORD
      remoteRef:
        key: secrets/mongodb/system
        property: cluster_admin_password
    - secretKey: MONGODB_CLUSTER_MONITOR_USER
      remoteRef:
        key: secrets/mongodb/system
        property: cluster_monitor_user
    - secretKey: MONGODB_CLUSTER_MONITOR_PASSWORD
      remoteRef:
        key: secrets/mongodb/system
        property: cluster_monitor_password
    - secretKey: MONGODB_USER_ADMIN_USER
      remoteRef:
        key: secrets/mongodb/system
        property: user_admin_user
    - secretKey: MONGODB_USER_ADMIN_PASSWORD
      remoteRef:
        key: secrets/mongodb/system
        property: user_admin_password