apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: vault
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  retrySettings:
    maxRetries: 4
    retryInterval: "5s"

  provider:
    vault:
      server: "http://vault-internal.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"

      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"