apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  retrySettings:
    maxRetries: 4
    retryInterval: "5s"

  provider:
    vault:
      server: "http://vault-internal:8200"
      path: "secret"
      version: "v2"

      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            audiences: ["external-secrets"]
            namespace: "vault"